- .github/actions/cancel-previous-workflows/action.yml
- .github/actions/release-tag-finder/action.yml
- .github/workflows/reusable-check-kotlin.yml
- .github/workflows/reusable-deploy-mortar.yml
- .github/workflows/reusable-github-release.yml
- .github/workflows/reusable-submit-sonarqube-analysis-kotlin.yml
- .gitignore
- app-name 기반의 Monorepo 형식 지원
- gradle 기반 build (gradle 설정을 그대로 사용할 수 있음)
- [kotlin coding style guide](https://go/kotlin-coding-style-guide) 및 [testing guide](https://go/kotlin-testing-guide)에 명시된 대로 설정된 프로젝트일 경우 lint, test 및 sonarqube를 통한 report등의 체크를 설정 해준다.
- lint는 reviewdog을 이용하여 아래 각각의 경우에 맞춰 report를 작성해준다.
- Pull Request : Review comment 형식으로 보고
- Push : report 형식으로 보고
- workflow_dispatch: Text 형식으로 보고
- test는 coverage를 스크린샷처럼 출력해준다.
- sonarqube 에 analysis를 등록하고 70% Coverage 확인에 실패할 경우 실패한다.
- 실패시 Failure Report artifact를 다운받아 실제 report들을 확인할 수 있다.
- 아래와 같이 mortar kotlin 프로젝트의 pipeline 을 구성해준다.
- check-kotlin을 사용해 버전을 검증하고 각 환경에 배포하는 pipeline을 구성한다.
- NonProd -> Dev, Testing, Staging ~~~ Prod -> Prod 형태로 배포된다.
- 각 배포 환경은 (Deploy - XX)는 environment 설정이 되어 있으므로, environment 에서 …
> Feat: 재사용 가능한 Kotlin Check 및 Mortar deploy workflow(check-kotlin, deploy-mortar)

- .github/workflows/reusable-nodejs-test.yml
- `reusable-nodejs-test` workflow를 추가합니다.
- [SC-8](https://ohouse.atlassian.net/browse/SC-8)
- 재사용할 수 있는 Node.js 테스트 workflow를 추가합니다.
프로젝트에 다음과 같이 사용할 수 있습니다:
> PR이 열릴 때마다 test 돌려주는 workflow 예제:
```yml
name: Node.js Test
on:
- pull_request
jobs:
test:
uses: bucketplace/ci/.github/workflows/reusable-nodejs-test.yml@main
with:
package-manager: npm # npm, yarn, yarn-legacy 선택 가능
test-command: custom-test # test 커맨드 명을 바꾸고 싶을 때 사용, 일반적으로 변경을 권장하지 않음
test-command-args: '--foobar' # test 커맨드에 전달할 옵션
```
**Note:** excerpted from https://github.com/bp-operator/github-action-ci-workflows/pull/1
> SC-8: `reusable-nodejs-test` workflow 추가

- .github/workflows/check-kotlin-gradle.yml
secret명이 항상 SONAR_TOKEN이 아닌 경우(저장소에 하나 이상의 패키지가 있을때)에 input으로 사용
> feat: check-kotlin-gradle에 sonar-token input 추가

- .github/workflows/check-golang.yml
- .github/workflows/deploy-go-package.yml
- go package를 배포해주는 CI를 만들었습니다.
- Lint 과정에서 Typecheck가 컴파일할 때 패키지를 못 찾는 문제가 생기지 않게 합니다.
- Lint 과정에서 컴파일 실패로 인한 패싱 문제 해결
- [기존 상태](https://github.com/bucketplace/feature-flag/actions/runs/3692551023/jobs/6251558371)
```console
/home/runner/work/_temp/reviewdog-fGvb9l/golangci-lint-1.50.1-linux-amd64/golangci-lint run --out-format line-number --config=.golangci.yaml ./...
level=warning msg="[runner] Can't run linter goanalysis_metalinter: inspect: failed to load package : could not load export data: no export data for \"go.dailyhou.se/gohouse/errors\""
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: inspect: failed to load package : could not load export data: no export data for \"go.dailyhou.se/gohouse/errors\"\n\n" …
```
> [COREPL-183] go package deploy ci

- .github/workflows/check-golang.yml
PR이 아닐 때 "Create Coverage Information"이랑 "Add Report To PR" skip 되서 "Add Result To Summary"를 실행하면 실페됩니다.
오류: "cat: code-coverage-results.md: No such file or directory"
> fix: PR이 아닐 때 "Add Result To Summary"step을 실행하지 않는다

- .github/actions/select-nodejs-pkg-manager/action.yml
- .github/workflows/check-nodejs.yml
- .github/workflows/reusable-changesets-prerelease.yml
- .github/workflows/reusable-changesets-publish.yml
- .github/workflows/reusable-changesets-snapshot.yml
- [FE Release Workflow Design Doc](https://docs.google.com/document/u/1/d/1crj7Q2QNJ6Wt5Aq-eTWjz9xt9OWxZDMI0cUdQJBgGOg/edit)에서 정의한 릴리즈 워크플로우를 각 서비스에서 손쉽게 구현할 수 있도록 패키징된 GitHub Workflows/Actions를 제공합니다.
- `select-nodejs-pkg-manager` action을 추가합니다: 자동으로 프로젝트의 package manager를 선택하고, install을 실행합니다.
> SC-59: FE release workflow 공통 GitHub workflows/actions 추가

- .github/workflows/check-kotlin-gradle.yml
jacoco-reports 파라미터 추가
비어있으면 원래 있었던 값대로
${{ inputs.app-path }}/build/reports/jacoco/test/jacocoTestReport.xml 사용합니다
파라미터 정할 때:
https://github.com/bucketplace/search-intro-page/actions/runs/4362008671/jobs/7626440689
> jacoco-reports: "application/api/build/reports/jacoco/test/jacocoTestReport.xml"
파라미터 없을 때 
https://github.com/bucketplace/search-intro-page/actions/runs/4362617457/jobs/7627720844
기본 값을 사용해서 파일 없기 때문에 실페했습니다.
> feat: jacoco-reports 파라미터 추가

- .github/actions/release-tag-finder/action.yml
deprecated된 `set-output` 을 `$GITHUB_OUTPUT` 파일로 대체합니다.
자세한 내용은 [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)를 참고해주세요.
아래의 명령을 통해 `set-output`을 찾았습니다:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=tag::${LATEST_TAG}"
echo "::set-output name=version::${LATEST_VERSION}"
```
```yml
echo "::set-output name=tag::${GEN_TAG}"
echo "::set-output name=version::${GEN_VERSION}"
```
**TO-BE**
```yml
echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
echo "version=${LATEST_VERSION}" >> $GITHUB_OUTPUT
```
```yml
echo "tag=${GEN_TAG}" >> $GITHUB_OUTPUT
echo …
```
> chore: replace deprecated `set-output` command with environment file

- .github/workflows/reusable-changesets-snapshot-with-comments.yml
- [FE release workflow](https://www.notion.so/ohouse/FE-Package-Release-Workflow-Guide-Setup-85a1cb88385b40239dc3ee446d67994a)에 comments 트리거하는 snapshot 워크플로우를 추가합니다.
https://www.notion.so/ohouse/FE-Package-Release-Workflow-Guide-Setup-85a1cb88385b40239dc3ee446d67994a?pvs=4#341aaba7ebaf4006b076238fc767a37f 에서 작동 테스트를 진행했습니다.
> SC-50: FE release workflow - comments로 트리거하는 snapshot 워크플로우 추가

- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
- README.md
- 본 CI 저장소 `main` 브랜치에 피쳐가 병합되면 버전 범프 후 자동으로 배포하도록 워크플로우를 추가합니다.
- `v*` 버전 태그 생성 후 `latest` 태그, GitHub Releases를 업데이트합니다.
- README 문서를 업데이트합니다.
- main에 병합되어야 테스트할 수 있습니다.
> SC-97: CI 저장소 `main` 브랜치에 피쳐가 병합되면 자동으로 배포하는 스크립트 추가

- .github/workflows/check-golang.yml
- golangci-lint 버전을 업데이트했습니다.
- Ginkgo 버전을 애플리케이션에서 사용 중인 버전으로 설치합니다.
- Go 버전을 go.mod에서 찾을 수 있게 합니다. `go-version`을 명시하면 해당 버전을 사용합니다.
- [테스트](https://github.com/bucketplace/watchcat/actions/runs/4559917209)
> [COREPL-599] Go & Ginkgo version auto detect

- .github/workflows/check-kotlin-gradle.yml
- `madrapps/jacoco-report` 의 [set-output 대응 패치한 버전](https://github.com/Madrapps/jacoco-report/releases/tag/v1.4)으로 액션을 최신화합니다.
> COREPL-950 fix: set-output in jacoco-report action

- .github/workflows/check-golang.yml
- SonarQube가 Deprecated 되어 Optional하게 사용할 수 있도록 플래그를 붙였습니다.
- Ginkgo를 아예 사용하고 있지 않은 경우 CLI 설치에 에러가 나는데, 기본 테스트 툴로 테스트를 할 수 있도록 플래그를 붙였습니다.
- [Test Action](https://github.com/bucketplace/feature-flag/actions/runs/5219417018/jobs/9422360495)
> chore: make ginkgo and sonarqube optional

- .github/workflows/deploy-go-package.yml
- 해당 PR 기준으로 0.4.1-rc.1을 배포하여 테스트할 예정입니다.
- [테스트 액션](https://github.com/bucketplace/gohouse/actions/runs/5207702576)
> COREPL-963 feat: add version metadata in github_output

- .github/workflows/check-nodejs.yml
- .github/workflows/reusable-changesets-prerelease.yml
- .github/workflows/reusable-changesets-publish.yml
- .github/workflows/reusable-changesets-snapshot-with-comments.yml
- .github/workflows/reusable-changesets-snapshot.yml
- Node.js 관련 워크플로우들의 기본 사용 Node.js 버전을 일괄 업그레이드합니다.
- 관련 논의: https://github.com/bucketplace/ohou.se-client/pull/3230#issuecomment-1650877362
- ㄴ v16 LTS 가 EoL이 됨에 따라 v18 LTS로 업그레이드
- 실제 각 저장소에서 워크플로우 실행 후 확인이 필요합니다.
> SC-299: 워크플로우 Node.js 버전 업그레이드

- .github/workflows/check-kotlin-gradle.yml
- `check-kotlin-gradle` workflow 에서 mortar multi-version 지원을 위하여  mortar-version 에 따라 mortar-runner 할당을 위한 태그를 지정하여줍니다.
- Dynamic Runs-On [Configurations](https://github.com/actions/runner/issues/409#issuecomment-1206725030)
- Mortar Multi-Version Github Action Runner [Configurations](https://www.notion.so/ohouse/Mortar-v2-f0aabff5bae249568c8cbba3faa9fd28?pvs=4#dabf4ded7e4041b58553ed460e49e760)
- 이 방법보다는, 사용하는 측에서 runs-on을 오버라이드 하는게 맞을까요? PR을 작성하고 알았는데, runs-on을 오버라이드도 되는 것 같은 느낌입니다. 맞을까요? @edwarddoh 
- `platform-service` [테스트](https://github.com/bucketplace/platform-service/pull/3) 완료
> COREPL-1211 feat: support mortar multi-version

- .github/workflows/reusable-sonarcloud-analysis-nodejs.yml
- ESLint의 경우 린트에 실패할 경우 non-zero exit(1)을 합니다. 하지만 이런 경우에도 리포트는 정상적으로 생성되며 SonarCloud에 이 리포트를 업로드해야 하므로 lint/lcov 명령이 실패하더라도 워크플로우 진행은 계속되어야 합니다.
- 따라서, 각 run 명령에 `continue-on-error: true` 를 추가합니다.
RC 배포 후 테스트합니다.
> SC-350: SonarCloud: FE 워크플로우에서 lint/lcov 명령이 non-zero exit 인 경우에도 재개 허용

- .github/workflows/check-web.yml
- [SonarCloud onboarding 중 논의](https://ohou-se.slack.com/archives/C05M5U8MKHQ/p1693992165675859?thread_ts=1693969722.905769&cid=C05M5U8MKHQ)된 FE 프로젝트 린팅 및 타입체크에 대한 대응 결론에 따라 web fe 프로젝트 전반에 사용할 수 있는 "Check Web" 하이브리드 워크플로우를 작성합니다.
- "Check Web" 하이브리드 워크플로우는 SonarCloud 프로젝트 설정이 없으면 [순수 Node.js 테스트 워크플로우](https://www.notion.so/CI-Node-js-Test-bfba167b7f9047f8a7df458b50d7e4d6)로 작동합니다.
- 만약 [SonarCloud: FE](https://www.notion.so/ohouse/SonarCloud-FE-a5c83f4034fb40c8be7d4ab5cf866164#41759839b18d4727b49a6fcc2c4b0392) 가이드에 따라 적용된 설정이 있는 경우, 리포트 업로드도 함께 진행하도록 기전이 변경됩니다.
[ohouse-divops](https://github.com/bucketplace/ohouse-divops) 프로젝트에 시범 적용함으로써 테스트합니다.
> [SC-389] Web FE 하이브리드 Test/SonarCloud 워크플로우 추가

- .github/workflows/check-web.yml
- Web Checks 워크플로우에 runner에서 가용가능한 메모리를 자동으로 산정해서 node 런타임 실행시 `--max-old-space-size` 옵션을 자동으로 포함시키도록 합니다.
commerce-web에서 테스트를 진행합니다.
https://github.com/bucketplace/commerce-web/actions/runs/6781026879/job/18430617611 에서 잘 돌아가는 것을 확인했습니다!
> [SC-451] Web Checks 워크플로우에 자동으로 --max-old-space-size 설정하는 스탭 추가

- .github/workflows/.protolint.yaml
- .github/workflows/check-protolint.yaml
* protolint 가 다양하게 쓰이고 하나의 repo 안에서 rule 관리하기 위해 만듭니다. 
* auth 에서 테스트 완료 (https://github.com/bucketplace/ohouse-auth/pull/169/files)
> [COREPL-1535] Add protolint in ci repo to use widely

- .github/workflows/check-web.yml
- `Web Checks` 워크플로우에서 memory limit이 cgroup-aware하도록 수정합니다.
- 가용 메모리의 75%만 사용합니다.
https://github.com/bucketplace/ohou.se-client/actions/runs/7334826721/job/19971982908 실패하는 액션에서 테스트하여 성공하는지 확인합니다.
> [COREPL-1565] `Web Checks` 워크플로우에서 memory limit이 cgroup-aware하도록 수정

- .github/workflows/mortar-build-and-push-action.yaml
- .github/workflows/mortar-deploy-action.yaml
- .github/workflows/mortar-preview-action.yaml
- .github/workflows/non-mortar-build-and-push-action.yaml
- .github/workflows/non-mortar-deploy-action.yaml
- .github/workflows/non-mortar-preview-action.yaml
- https://github.com/bucketplace/search-backend 에서 모노레포로 전환하면서 여러 서버에서 사용할 수 있는 배포 action을 만들었는데(광고팀 모노레포 action 참고해서),
- 생각해보니 저희 검색팀 다른 레포 혹은 다른팀 에서도 다같이 사용할 수 있으면 좋을 것 같아서 추가합니다.
- 사용예시는 https://github.com/bucketplace/search-backend/blob/d3ea18ab6812faf86b5aa6a13564fab4274ebd9b/.github/workflows/search-application-server-deploy.yaml#L1 여기 보면 됩니다.
> [SEARCH-2072] add mortar, non-mortar deploy action

- .github/actions/latest-tag-finder/action.yml
- search-backend repository에서는 search-application-server, search-application-server-global 이라는 두앱이 존재합니다.
- 그래서 search-applciation-server-global-0.0.1, search-application-server-0.0.1 등의 태그가 공존하게됩니다.
- 그래서 search-application-server 기준으로 태그를 가져오면 search-application-server-global의 태그가 잡히게 됩니다.
- 이러한 현상을 제거하기위해서 LATEST_TAG를 가져올 때 prefix 뒤에 바로 version만 있는 태그들만 가져올 수 있도록 수정을 제안합니다.
> [SEARCH-2424] release 태그 추출시 이상한 태그 들어오는 버그 수정

- .github/workflows/mortar-preview-action.yaml
- global에서 ingress host를 httpProxy.host값을 사용하고 있습니다. 
- 그래서 global지원을 위해 파라미터로 추가합니다.
- korea에서는 httpProxy.host가 아닌 기본값을 사용해야하는데, 기본값은 https://github.com/bucketplace/ops-monster-v2/blob/99200770f5ba5b249f531e0e16fe22d3aa691600/opsmonster/application/serializers.py#L586 여기에서 확인했습니다. 
> [SEARCH-2072] add ingress host key parameter

- .github/actions/select-nodejs-pkg-manager/action.yml
- .github/actions/setup-nodejs/action.yaml
- .github/workflows/check-nodejs.yml
- .github/workflows/check-web.yml
- .github/workflows/reusable-changesets-prerelease.yml
- .github/workflows/reusable-changesets-publish.yml
- .github/workflows/reusable-changesets-snapshot.yml
- .github/workflows/reusable-sonarcloud-analysis-nodejs.yml
- Self-hosted runner와 함께 사용하는 것을 가정하는 FE Node.js 셋업 액션을 추가합니다.
- 다른 액션과 조합하여 워크플로우를 구성할 수 있도록 합니다.
- 추후 모든 Node.js 프로젝트에 적용되어야 하는 pre-condition (공용 글로벌 CLI 도구 설치 등)을 본 액션에서 처리합니다.
- 올바르지 않은 필드를 기존 CI 설정에서 제거합니다.
- 기존 CI 워크플로우를 업데이트합니다.
~~`ohouse-divops`에서 테스트를 진행합니다.~~ 액션의 경우 저장소에서 재사용 워크플로우에서 참조시 바로 테스트가 어려워서 병합 후 rc로 테스트를 진행합니다.
> [SC-635] FE Node.js 셋업 액션 추가
