.github/workflows/reusable-nodejs-test.yml

- https://github.com/bucketplace/ci/pull/3#discussion_r1033184536
- 깜빡 잊고 제거하지 못한 workflow 조건을 제거합니다.
N/A

SC-8-2: `reusable-nodejs-test` workflow 오타 수정

---

.github/workflows/reusable-nodejs-test.yml

- `reusable-nodejs-test`에서 패키지 매니저를 자동으로 선택하도록 수정합니다.
- `Run test` 단계에서 엉뚱한 커맨드를 실행하던 문제를 수정합니다.
- https://github.com/bucketplace/private-file-server/actions/runs/3562856495 에서 manual하게 테스트를 해보았습니다.

SC-10: `reusable-nodejs-test` workflow 패키지 매니저 자동으로 선택하도록 수정

---

.github/workflows/check-nodejs.yml
.github/workflows/reusable-nodejs-test.yml

- https://github.com/bucketplace/ci/pull/5#issuecomment-1330127402 에서 피드백 받은 base dir(working directory) 옵션을 추가합니다. @edwarddoh 
- node.js 버전 지정 옵션을 추가합니다. cc @bucketressi 
- xpc 저장소에서 테스트했습니다: https://github.com/bucketplace/ci/pull/7#discussion_r1041892480

SC-11: "Run Node.js Test" reusable 액션에 base dir 및 node.js 버전 지정 옵션 추가

---

.github/workflows/check-golang.yml

sonarqube-exclusions 옵션을 추가합니다.
[테스트 workflow](https://github.com/bucketplace/feature-flag/actions/runs/3691337664)

chore: add sonarqube exclusions option

---

.github/actions/load-build-cache/action.yml
.github/actions/store-build-cache/action.yml
.github/workflows/check-kotlin-gradle.yml

Cache 기능 지원하는 mortar-runner를 활용할 수 있도록 load, store build cache actions 생성 및 kotlin 빌드 시에 load -> build -> store 형태로 캐쉬 활용하도록 변경
- https://github.com/bucketplace/infra-helm/pull/91
- https://github.com/bucketplace/mortar-deploy-action/pull/10
cache-test 브랜치로 테스트

[COREPL-254] feat: Mortar Build Cache 적용

---

.github/workflows/deploy-go-package.yml

chore: update pack version

---

.github/workflows/reusable-changesets-prerelease.yml
.github/workflows/reusable-changesets-snapshot.yml

* changeset을 활용한 배포 자동화 workflow를 추가합니다.
* prerelease
* snapshot 

[COMMWEB-381] feat: prerelease 및 snapshot 배포 workflow

---

.github/actions/select-nodejs-pkg-manager/action.yml

- https://github.com/bucketplace/ci/pull/15 에서 적용한 액션에 오타가 있어서 수정합니다 ㅠㅠ
N/A

fix: select-nodejs-pkg-manager 액션내 오타를 수정합니다

---

.github/workflows/reusable-changesets-snapshot.yml

- [FE Pakcage Release Workflow](https://www.notion.so/ohouse/FE-Package-Release-Workflow-Guide-08071f6a5e0b4f00a3ab1f59cb180414) - snapshot 액션에서 릴리즈된 패키지/버전 정보를 알 수 있도록 출력합니다.
N/A

SC-79: FE release workflow - snapshot 액션에서 릴리즈된 패키지/버전 정보 알 수 있도록 출력

---

.github/workflows/deploy-go-package.yml

- pack의 버저닝 피처를 위한 action을 수정합니다.
- 해당 [PR](https://github.com/bucketplace/gohouse/pull/39)이 머지 되고 pack이 v0.4.0.rc-1으로 배포되어야 테스트할 수 있습니다.
- 해당 [PR](https://github.com/bucketplace/gohouse/pull/39)에서 사용합니다.

COREPL-619 feat: add workflow for pack increment feature

---

.github/workflows/check-golang.yml

- [Test Action](https://github.com/bucketplace/feature-flag/actions/runs/5240518090/jobs/9461459265)

fix: double and operations

---

.github/workflows/deploy-go-package.yml

- 아웃풋 설정과 Job 이름을 수정합니다.
- [테스트 중...](https://github.com/bucketplace/feature-flag/pull/138)

fix: deploy output

---

.github/workflows/deploy-go-package.yml

- Pack CLI 버전을 올립니다.
- [Pre Release Version](https://github.com/bucketplace/feature-flag/actions/runs/5474214031)
- [Minor Patch](https://github.com/bucketplace/feature-flag/actions/runs/5483942438)
- Pre Release 버전을 Latest로 인지하지 않음

feat: update pack

---

.github/workflows/release.yml
README.md

- 릴리즈가 잘 동작하지 않던 문제 (태그 변경 안됨 등) 를 수정합니다.
- bucketplace/ci/.github/actions/multimodule-changelog@latest 를 최대한 활용합니다.

fix: 제대로 동작하지 않는 release workflow를 복구합니다.

---

.github/workflows/reusable-sonarcloud-analysis-nodejs.yml

- SoanrCloud: FE 워크플로우에 SONAR_TOKEN을 필수 secrets로 추가합니다.
병합 후 RC 릴리즈로 테스트합니다.

[SC-350] SonarCloud: FE 워크플로우에 SONAR_TOKEN 필수 시크릿으로 추가

---

.github/workflows/check-web.yml

- Web Checks 액션에 Docker Hub 로그인 step을 추가하여 [rate-limit](https://www.notion.so/ohouse/dockerhub-rate-limit-295d7b40cbea42b0bf21f21a599ed4d4) 이슈를 방지합니다.
Workflow 적용 후 실제로 rate-limit 오류가 발생하는지 확인해야 합니다. (...)

[SC-407] Web Checks 액션에 Docker Hub 로그인 step 추가

---

.github/workflows/check-web.yml

- Web Checks 워크플로우 app-path가 cwd에 더블로 쌓이는 이슈를 수정합니다.
- https://github.com/bucketplace/ads/actions/runs/6322472521/job/17168162566?pr=766

[SC-1] Web Checks 워크플로우 cwd 이슈 수정

---

.github/workflows/check-web.yml

- Web Checks 워크플로우에 prepare 스탭을 추가합니다.
- Sonarcloud prepare 스탭에서 커스텀 `sonarcloud` 커맨드를 사용하지 않던 부분을 수정합니다.
- [ohouse-divops](https://github.com/bucketplace/ohouse-divops) 저장소에서 테스트합니다.

[SC-420] Web Checks 워크플로우에 prepare 스탭 추가

---

.github/workflows/reusable-changesets-publish.yml

- changeset publish 시 pre exit 로 인해 오류가 발생합니다.
- https://github.com/bucketplace/ohouse-web-foundation/actions/runs/6811722192/job/18522635117#step:9:10

[O2OWEB-0] config: pre cmd 제거

---

.github/workflows/reusable-changesets-publish.yml

- 패키지 인스톨 시, production 으로 설정되어 있어 pnpm install 시, 빌드에 필요한 모듈이 설치되지 않고 있습니다.
- 빌드 시에만 NODE_ENV=production 을 설정합니다.

[COMWEB-0] config: 빌드 스크립트 호출 시 env production 설정

---

.github/actions/setup-mortar/dist/index.js
.github/actions/setup-mortar/index.js

* background: mortar multi-version support 사용해서 pasf-partner-auth-api 가 prod 배포하려는 시점에 배포가 안되는 이슈 발견. 
- 해당 failed action link - https://github.com/bucketplace/ohouse-auth/actions/runs/7382109097/attempts/1
* 로그 자세히 보니 remote 변경점 생기고 나서 remote 에 해당 버전을 업데이트 안해줘서 예전 로그가 나왔다는것을 확인 했습니다. 
* 자세한 thought process 는 간단하게 [노션](https://www.notion.so/ohouse/mortar-runner_file-randomly-created-d95aaec38e2e408b83242e55e50cedc8?pvs=4)에 정리 했습니다. 
* what's next? 추후 TODO 에 있는 버전 자동으로 가져와 주는 작업 할 예정입니다. 

[COREPL-1573] Fix: Update Setup Mortar Version (ignore-stats)

---

.github/actions/multimodule-changelog/action.yml

[SEARCH-2377] multimodule-changelog bump bug fix

---

.github/workflows/mortar-preview-action.yaml
.github/workflows/non-mortar-preview-action.yaml

- mortar preview 예시: https://github.com/bucketplace/search-backend/blob/84cb3a8c7cd3de358cdc35ee64802df5d60596ba/.github/workflows/curated-search-preview.yaml#L8-L7
- non mortar preview 예시: https://github.com/bucketplace/search-backend/blob/a76fb8cf3b8e52d3fbf266b28bbfb23d4c26fb45/.github/workflows/autocomplete-preview.yaml#L10

[SEARCH-2072] mortar preview, non-mortar preview action

---

.github/workflows/mortar-preview-action.yaml

[SEARCH-2365] change yq action

---

.github/workflows/mortar-build-and-push-action.yaml
.github/workflows/mortar-preview-action.yaml

Revert "[SEARCH-2365] change yq action"

---

.github/workflows/mortar-preview-action.yaml

- preview action에서 변경된 버전을 사용하는것이아닌, 기존버전으로 배포되도록 되어 있었습니다.

[SEARCH-2072] mortar preview action version bug fix

---

.github/workflows/mortar-build-and-push-action.yaml
.github/workflows/mortar-deploy-action.yaml

[SEARCH-2591] mortar 배포stub-only 파라미터 추가

---

.github/actions/setup-mortar/dist/index.js
.github/actions/setup-mortar/index.js

* https://github.com/bucketplace/mortar/pull/118 <- fix multi-module 권한 관련해서 추후에 cli cmd 의 디버깅 및 확인을 위해서 버전 업데이트 진행 합니다.
* 참고로 아직 해당 버전 릴리즈는 안했지만 추후 릴리즈 후 사용을 위한 변화 입니다. 
* `ncc build index.js`

[COREPL-1611] Fix Mortar multi-module

---

.github/workflows/check-web.yml

- Web Checks 워크플로우에 large runner 지원을 추가합니다.
- Large runner는 https://ohouse.atlassian.net/browse/DEVOPS-3020 에서 추가되었습니다.
main 병합 후 rc 버전으로 [ohou.se 저장소](https://github.com/bucketplace/ohou.se)서 테스트를 진행합니다.

[OHSWEB-4785] Web Checks 워크플로우 large runner 지원 추가

---

.github/workflows/check-nodejs.yml
.github/workflows/check-web.yml
.github/workflows/reusable-changesets-prerelease.yml
.github/workflows/reusable-changesets-publish.yml
.github/workflows/reusable-changesets-snapshot.yml
.github/workflows/reusable-sonarcloud-analysis-nodejs.yml

- 앞서 변경한 PR https://github.com/bucketplace/ci/pull/68 에서 오타가 있어 이를 수정합니다.
- NPM_TOKEN -> NEXUS_NPM_TOKEN
N/A

[SC-1] setup-node 액션에 전달하는 NPM_TOKEN 오타 수정
